DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'stock') THEN
        CREATE ROLE stock LOGIN;
    END IF;
END
$$;

ALTER ROLE stock NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT CONNECT ON DATABASE stock_forecasting TO stock;
GRANT USAGE ON SCHEMA public TO stock;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO stock;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO stock;
REVOKE INSERT, UPDATE, DELETE ON authorization_policy_sets FROM stock;
REVOKE UPDATE, DELETE ON model_lifecycle_events FROM stock;
